# Generated by Django 4.1.13 on 2024-02-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_login_alter_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], max_length=20),
        ),
    ]
